version: '2'
services:
  fixedassets-app:
    image: fixedassets
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fixedassets-postgresql:5432/fixedAssets
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://fixedassets-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://fixedassets-elasticsearch:9200
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 12001:12001
  fixedassets-postgresql:
    extends:
      file: postgresql.yml
      service: fixedassets-postgresql
  fixedassets-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: fixedassets-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
